### **1. Installing all required libraries**

In [ ]:
pip install polars pandas sqlalchemy psycopg2 pyarrow

Collecting polars
  Downloading polars-1.44.1-py3-none-any.whl.metadata (11 kB)
Collecting polars-runtime-32==1.44.1 (from polars)
  Downloading polars_runtime_32-1.44.1-cp310-abi3-win_amd64.whl.metadata (1.5 kB)
Downloading polars-1.44.1-py3-none-any.whl (865 kB)
   ---------------------------------------- 0.0/865.2 kB ? eta -:--:--
   ---------------------------------------- 865.2/865.2 kB 11.8 MB/s  0:00:00
Downloading polars_runtime_32-1.44.1-cp310-abi3-win_amd64.whl (53.7 MB)
   ---------------------------------------- 0.0/53.7 MB ? eta -:--:--
   ---- ----------------------------------- 6.3/53.7 MB 31.9 MB/s eta 0:00:02
   ---------------- ----------------------- 22.8/53.7 MB 56.3 MB/s eta 0:00:01
   -------------------------------- ------- 43.5/53.7 MB 70.2 MB/s eta 0:00:01
   ---------------------------------------- 53.7/53.7 MB 68.0 MB/s  0:00:00
Installing collected packages: polars-runtime-32, polars

   ---------------------------------------- 0/2 [polars-runtime-32]
   ---------------------------------------- 0/2 [polars-runtime-32]
   ---------------------------------------- 0/2 [polars-runtime-32]
   ---------------------------------------- 0/2 [polars-runtime-32]
   ---------------------------------------- 0/2 [polars-runtime-32]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   -------------------- ------------------- 1/2 [polars]
   ---------------------------------------- 2/2 [polars]

Successfully installed polars-1.44.1 polars-runtime-32-1.44.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# import libraries
import polars as pl
import pandas as pd
from sqlalchemy import create_engine
import os
import shutil # shell utilities for copying, deleting and archiving files
import pyarrow as pa
import time

In [ ]:
# Comparing between polars and pandas 
csv = pl.read_csv("../data/sales_data.csv").lazy()
csv_pds = pd.read_csv("../data/sales_data.csv")

In [14]:
csv.collect()

shape: (1_000, 14)
┌────────────┬────────────┬───────────┬────────┬───┬──────────┬────────────┬───────────┬───────────┐
│ Product_ID ┆ Sale_Date  ┆ Sales_Rep ┆ Region ┆ … ┆ Discount ┆ Payment_Me ┆ Sales_Cha ┆ Region_an │
│ ---        ┆ ---        ┆ ---       ┆ ---    ┆   ┆ ---      ┆ thod       ┆ nnel      ┆ d_Sales_R │
│ i64        ┆ str        ┆ str       ┆ str    ┆   ┆ f64      ┆ ---        ┆ ---       ┆ ep        │
│            ┆            ┆           ┆        ┆   ┆          ┆ str        ┆ str       ┆ ---       │
│            ┆            ┆           ┆        ┆   ┆          ┆            ┆           ┆ str       │
╞════════════╪════════════╪═══════════╪════════╪═══╪══════════╪════════════╪═══════════╪═══════════╡
│ 1052       ┆ 2/3/2023   ┆ Bob       ┆ North  ┆ … ┆ 0.09     ┆ Cash       ┆ Online    ┆ North-Bob │
│ 1093       ┆ 4/21/2023  ┆ Bob       ┆ West   ┆ … ┆ 0.11     ┆ Cash       ┆ Retail    ┆ West-Bob  │
│ 1015       ┆ 9/21/2023  ┆ David     ┆ South  ┆ … ┆ 0.2      ┆ Bank       ┆ Retail    ┆ South-Dav │
│            ┆            ┆           ┆        ┆   ┆          ┆ Transfer   ┆           ┆ id        │
│ 1072       ┆ 8/24/2023  ┆ Bob       ┆ South  ┆ … ┆ 0.02     ┆ Credit     ┆ Retail    ┆ South-Bob │
│            ┆            ┆           ┆        ┆   ┆          ┆ Card       ┆           ┆           │
│ 1061       ┆ 3/24/2023  ┆ Charlie   ┆ East   ┆ … ┆ 0.08     ┆ Credit     ┆ Online    ┆ East-Char │
│            ┆            ┆           ┆        ┆   ┆          ┆ Card       ┆           ┆ lie       │
│ …          ┆ …          ┆ …         ┆ …      ┆ … ┆ …        ┆ …          ┆ …         ┆ …         │
│ 1010       ┆ 4/15/2023  ┆ Charlie   ┆ North  ┆ … ┆ 0.29     ┆ Cash       ┆ Online    ┆ North-Cha │
│            ┆            ┆           ┆        ┆   ┆          ┆            ┆           ┆ rlie      │
│ 1067       ┆ 9/7/2023   ┆ Bob       ┆ North  ┆ … ┆ 0.21     ┆ Bank       ┆ Retail    ┆ North-Bob │
│            ┆            ┆           ┆        ┆   ┆          ┆ Transfer   ┆           ┆           │
│ 1018       ┆ 4/27/2023  ┆ David     ┆ South  ┆ … ┆ 0.06     ┆ Bank       ┆ Online    ┆ South-Dav │
│            ┆            ┆           ┆        ┆   ┆          ┆ Transfer   ┆           ┆ id        │
│ 1100       ┆ 12/20/2023 ┆ David     ┆ West   ┆ … ┆ 0.01     ┆ Bank       ┆ Online    ┆ West-Davi │
│            ┆            ┆           ┆        ┆   ┆          ┆ Transfer   ┆           ┆ d         │
│ 1086       ┆ 8/16/2023  ┆ Alice     ┆ East   ┆ … ┆ 0.14     ┆ Cash       ┆ Online    ┆ East-Alic │
│            ┆            ┆           ┆        ┆   ┆          ┆            ┆           ┆ e         │
└────────────┴────────────┴───────────┴────────┴───┴──────────┴────────────┴───────────┴───────────┘

In [11]:
csv_pds.head(5)

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2/3/2023,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,4/21/2023,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,9/21/2023,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,8/24/2023,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,3/24/2023,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

### **1. Pipeline construction**

In [ ]:
# Environment variables
DB_URL="postgresql://username:password@localhost:5432/myDatabase"
TABLE_NAME ="sales_data"
SOURCE_FOLDER ="../data"
DESTINATION_FOLDER ="../output"

# PostgreSQL connection
engine = create_engine(DB_URL)

# Creation of a list
csv_file = [f for f in os.listdir(SOURCE_FOLDER) if f.endswith('.csv')]

if not csv_file:
    print("No csv file found in the source folder.")
else:
    for f in csv_file:
        csv_path = os.path.join(SOURCE_FOLDER, f)
        print(f"Processing file: {csv_path}")
        
        try:
            # Load data
            df_sales = pl.read_csv(csv_path)
            
            # Apply transformations
            df_sales = df_sales.drop(["Region_and_Sales_Rep"])
            df_sales = df_sales.with_columns(
                pl.col("Sale_Date").str.to_date("%m/%d/%Y")
            )
            # Convert Polars to Pandas for writing to PostgreSQL
            #df_sales = df_sales.to_pandas()
            
            # Write to PostgreSQL
            with engine.connect() as con:
                df_sales.write_database(
                    table_name=f"{TABLE_NAME}s", 
                    connection=con, 
                    if_table_exists="replace"
                )
                print(f"Data written to table: {TABLE_NAME}s")
            
            # Move the processed file
            destination_path = os.path.join(DESTINATION_FOLDER, f)
            time.sleep(1)  
            shutil.move(csv_path, destination_path)
            print(f"File moved to {destination_path}")
            
        except Exception as e:
            print(f"Error processing file {f}: {e}")

print("Processing completed.")

Processing file: ../data\sales_data.csv
Data written to table: sales_datas
File moved to ../output\sales_data.csv
Processing completed.